version: 4.2.{build}

image:
- Visual Studio 2019

configuration:
- "3.8"
- "3.7"
- "3.6"

build_script:
  - call "C:\Program Files (x86)\Microsoft Visual Studio\2019\VC\Auxiliary\Build\vcvars32.bat"
  - md build
  - cd build
  - cmake -DPYTHON_VERSION=%CONFIGURATION% -G "Visual Studio 16 2019" -A Win32 ..
  - cmake --build . --target NatlinkModule